### ISSUE TITLE
Fix bug in class conflict

### ISSUE THREAD

**Issue by sjoann** [AY2223S1-CS2103T-T09-4/tp#113]
To free up the class slot after a person is deleted

Current implementation bug:
```
edit 2 dt/2022-10-12 1300-1400
delete 2
edit 1 dt/2022-10-12 1300-1400
```
will yield `There is a conflict between the class timings` when in reality there shouldn't be after `2`'s deletion.

**Comment by cadencjk** [comment]
Similar to #111, will close #111.
