### ISSUE TITLE
As a forgetful tutor, I will be warned if the addition of a new session will clash with a previously set session

### ISSUE THREAD

**Issue by sjoann** [AY2223S1-CS2103T-T09-4/tp#13]
... so that I can have a peace of mind that my students’ sessions do not clash.

**Comment by cadencjk** [comment]
Allow dt/ to be added on top of the existing required "add tags"

Search through current list of class timing to ensure there is no clash when a student with dt/ is added

**Comment by cadencjk** [comment]
Implemented in MS1.2b.
