### ISSUE TITLE
Bug: Consecutive special characters not allowed in email

### ISSUE THREAD

**Issue by gnahzeus** [AY2223S1-CS2103T-T09-4/tp#142]
Current constraints for email is:

Emails should be of the format local-part@domain and adhere to the following constraints:
**1. The local-part should only contain alphanumeric characters and these special characters, excluding the parentheses, (+_.-)**. The local-part may not start or end with any special characters.
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.

However, consecutive special characters are not allowed in the local-part. 
E.g. jon-.snow@gmail.com

To do: Change condition of email in description, comments and user guide to adhere to this specification: 

Emails should be of the format local-part@domain and adhere to the following constraints:
**1. The local-part should only contain alphanumeric characters.** 
2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels separated by periods.
The domain name must:
    - end with a domain label at least 2 characters long
    - have each domain label start and end with alphanumeric characters
    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.

**Comment by Echomo-Xinyu** [comment]
Violating commonly accepted constraints for email. Out of scope.
