### ISSUE TITLE
As a busy tutor, I can use shorter commands

### ISSUE THREAD

**Issue by cadencjk** [AY2223S1-CS2103T-T09-4/tp#21]
... so that I can simplify the commands by using aliases.

**Comment by Echomo-Xinyu** [comment]
- Propose alternative alias for the command keyword, e.g. `a` in place of `add`, `e` in place of `edit`, and bring up in the group for review;
- Incorporate agreed alternative alias into the code base
- Add relevant test cases for the new alternative keywords (which will be replicating the code base of command parsers part)

**Comment by Echomo-Xinyu** [comment]
Due to evolving requirements, the story is no longer considered suitable for the project.
