### ISSUE TITLE
Hunt for Bugs in DG

### ISSUE THREAD

**Issue by Echomo-Xinyu** [AY2223S1-CS2103T-T09-4/tp#211]

**Comment by sjoann** [comment]
update table of content to include hyperlinks for implementation and design considerations, include missing fields for find by

**Comment by Echomo-Xinyu** [comment]
> update table of content to include hyperlinks for implementation and design considerations, include missing fields for find by

I think it would be good to add it as a separate issue so that we can mark it closed when done with fixing. ;)

**Comment by Echomo-Xinyu** [comment]
Remove the "proposed" in `find-by` section in DG.
