### ISSUE TITLE
Fix UI bug which fixes too long address UI issue (overflow)

### ISSUE THREAD

**Issue by seanflyyy** [AY2223S1-CS2103T-T09-4/tp#224]

**Comment by Echomo-Xinyu** [comment]
This UI is resulted from edit the two datetime field into today with the default UI, setting (screensize) and default data.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/25452497/199084117-64dbdbbe-6f3d-4775-a6bc-04131be5da9f.png">

**Comment by cadencjk** [comment]
Closed in #310
