### ISSUE TITLE
[PE-D][Tester A] Error message for mark misleading

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-4/tp#231]
the error message for invalid index of mark says the person index is wrong. a bit misleading

![image.png](https://raw.githubusercontent.com/LuYiting0913/ped/main/files/43516b7a-7d89-4e06-bf25-23c77ad32a3a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LuYiting0913/ped#5

**Comment by seanflyyy** [comment]
@cadencjk in the UG already said that the index refers to the one on the right
