### ISSUE TITLE
[PE-D][Tester A] Each student only has one class

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-4/tp#234]
when i add a new class to a student, the previous class record will be deleted.
not very ideal because a student can have multiple classes
![image.png](https://raw.githubusercontent.com/LuYiting0913/ped/main/files/3068cd90-befd-42bd-b8a6-87a41915d54a.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: LuYiting0913/ped#8

**Comment by seanflyyy** [comment]
Not in scope / Product design
