### ISSUE TITLE
[PE-D][Tester A] Sort field name not case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-4/tp#237]
same for class and name
![image.png](https://raw.githubusercontent.com/LuYiting0913/ped/main/files/74fbb284-c7db-464b-aa98-6e622b4f3e5a.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: LuYiting0913/ped#11

**Comment by seanflyyy** [comment]
Already stated in the UG
