### ISSUE TITLE
[PE-D][Tester A] Sort based on class time not accurate

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-4/tp#239]
Nov before Oct
![image.png](https://raw.githubusercontent.com/LuYiting0913/ped/main/files/fd3029be-e7eb-4d52-b7e7-2812929cd3ce.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: LuYiting0913/ped#13

**Comment by seanflyyy** [comment]
Update user guide to more specific also unless this is a bug
