### ISSUE TITLE
As a lazy tutor, I can use a single command to delete multiple students

### ISSUE THREAD

**Issue by cadencjk** [AY2223S1-CS2103T-T09-4/tp#24]
... so that I can delete multiple students quickly.

**Comment by Echomo-Xinyu** [comment]
The procedure should be similar to #27:

- Create a new command `deleteMultiple` which takes in an array of conditions, perhaps different prefix tags so that it can find students based on different conditions being met
- Create test cases for the `deleteMultiple` command

**Comment by sjoann** [comment]
- Free up classes slot using removeExistingClass
