### ISSUE TITLE
[PE-D][Tester D] Entering repeated indices in the `delete` command leads to unexpected behavior.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-4/tp#244]
To reproduce, add 3 students to the student list, and run `delete 2 2`, it would reject the command, but still delete student 2 and student 3 from the list. Furthermore, the statistics would still reflect the original number of students.
![image.png](https://raw.githubusercontent.com/ngxingyu/ped/main/files/0817e151-803c-4952-a445-18b52ade8a2a.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ngxingyu/ped#2

**Comment by seanflyyy** [comment]
Reject duplicate values
Follow up with reviewer on how to reproduce error
