### ISSUE TITLE
[PE-D][Tester D] Edit command fails for large integer inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-4/tp#245]
Entering a moderately large integer input is not possible since it throws an error.

![image.png](https://raw.githubusercontent.com/ngxingyu/ped/main/files/b3ff95d8-9104-4e85-85eb-9983a37b04a2.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ngxingyu/ped#3

**Comment by seanflyyy** [comment]
Same as the other issue
