### ISSUE TITLE
[PE-D][Tester C] Accept non-integer values for amount

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-4/tp#271]
Currently rates per class only accepts integer values. This does not cover cases where the rate is not an integer (e.g. the user charges $35.50 for a class). Same applies to Amount owed and Amount paid.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: neosunhan/ped#5

**Comment by seanflyyy** [comment]
This should be quite big

**Comment by Echomo-Xinyu** [comment]
Allowing float is considered a good-to-have feature but in real practice, most private tutors charge by the exact amount like $40 per hour and that is the rationale for integers to hold monetary value. Due to the feature freeze in v1.4, this change is not planned.
