### ISSUE TITLE
[PE-D][Tester C] Undo command does not work with find

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-T09-4/tp#272]
After a find command (e.g. `find n/alex`), the undo command does not return the list of students to the previous state.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: neosunhan/ped#6

**Comment by seanflyyy** [comment]
There is a bug in the undo when you run `edit 1 n/John` then you run `find t/Python`, when you run undo, it doesn't do anything

**Comment by Echomo-Xinyu** [comment]
> There is a bug in the undo when you run `edit 1 n/John` then you run `find t/Python`, when you run undo, it doesn't do anything

This bug is not really true as the `undo` will undo the change but not display as explained during meeting.
