### ISSUE TITLE
As a busy tutor, I can sort my students based on alphabetical order

### ISSUE THREAD

**Issue by cadencjk** [AY2223S1-CS2103T-T09-4/tp#4]
... so that I can find the details of my students quicker.

**Comment by sjoann** [comment]
- Implement a comparison method to compare the Name of the Persons 
- Update the filtered list with the sorted order

**Comment by seanflyyy** [comment]
Should be able to take in these different forms:
- sort asc/ n/
- sort n/ asc/
- sort desc/ n/
- sort n/ desc/
