### ISSUE TITLE
Add the ability to edit next of kin phone numbers

### ISSUE THREAD

**Issue by cadencjk** [AY2223S1-CS2103T-T09-4/tp#44]
Update phone number that will be of 8 digits in length, starting with 8 or 9

**Comment by Echomo-Xinyu** [comment]
Issue closed as this has already been implemented in AB3.

**Comment by Echomo-Xinyu** [comment]
The issue has been modified to avoid confusion with existing functionality.

**Comment by gnahzeus** [comment]
Resolved by #103.
