### ISSUE TITLE
As a busy tutor, I can add the date of the next class in a more natural format (eg: Nearest Tuesday)

### ISSUE THREAD

**Issue by Echomo-Xinyu** [AY2223S1-CS2103T-T09-4/tp#5]
... so that I do not need to search for the date manually.

**Comment by sjoann** [comment]
eg. edit 1 dt/tue 1500-1600 will set the class date to the oncoming tuesday 3pm-4pm

**Comment by seanflyyy** [comment]
- There should be short forms of the days, Mon, Tue, Wed, Thu, Fri, Sat, Sun
